### ISSUE TITLE
End of the show ratings/reviews

### ISSUE THREAD

**Issue by smaugnbeans** [art-re-art/art-re-art-web#4]
When Nancy specifies, send out a notification for people to rate the experience 
ratings/reviews go to nancy, not public

**Comment by nancyvannoppen** [comment]
great idea smaugnbeans!

**Comment by overshard** [comment]
This is more of a mobile task then a web one is it not? Or are we wanting to do something on the web for this too? If it is just mobile please close this one and recreate there.

**Comment by overshard** [comment]
I'm assuming we are sending this out on mobile since it doesn't make since to do it on the website. We can request people to review it as they leave via notifications. Closing this.
