### ISSUE TITLE
Add Art model and API to artists app

### ISSUE THREAD

**Issue by nancyvannoppen** [art-re-art/art-re-art-web#5]
- [x] Create art model in artists app
- [x] Create serializer and viewset in api app
- [x] Add art serializer to artist serializer
- [x] Add art list and component to artist page
- [x] Update artist component to use featured_art image instead of qrcode
- [x] Inline admin with ArtistWork?
- [x] Issue with api_url artistworkimage-detail

photo, title, year, image, description, and artist (see art upload on signup form)

**Comment by smaugnbeans** [comment]
@overshard issue with artistworkimage-detail in artreart.com/api/artistwork/ .. not sure how to fix that

Templates still need to be added/edited

**Comment by overshard** [comment]
These should all be complete now
