### ISSUE TITLE
Improve navigation

### ISSUE THREAD

**Issue by nancyvannoppen** [art-re-art/art-re-art-web#6]
- [x] Create better URLs, use slug for specific artists, events, art instead of id
- [ ] Add breadcrumbs under page header
- [x] Improve mobile support of navigation
- [x] Improve sidebar event block design
- [x] Make sure sidebar adjusts to work on all possible standard resolutions
- [x] transform-origin for different breakpoints
- [x] make event block fixed width to avoid weird transition

**Comment by overshard** [comment]
Everything done here except breadcrumbs since header is being reworked we can do that there.
