### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by nancyvannoppen** [art-re-art/art-re-art-web#7]
- [x] Install react-ga with NPM
- [x] Add initial GA configuration
- [x] Add tracking for various events, ex. artist signup abandon, adding more work to artist signup

**Comment by overshard** [comment]
Will probably use https://github.com/react-ga/react-ga

Google analytics tracking code is UA-141212265-1

**Comment by overshard** [comment]
This is looking good, going to mark this as complete and we can progressively add more tracking as we find good use cases.
